name: Run coverage tests

on: [push, pull_request]

permissions:
  contents: write

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the main branch from the repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install PHP Dependencies
      run: composer update

    - name: Copy example .env file
      run: |
        cp .env.example .env
        sed -i 's/_SECRET_DB_PASSWORD/$DB_PASSWORD/g' .env
      env:
        DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}


    - name: Install App key
      run: php artisan key:generate

    - name: Run Tests
      run: php artisan test --coverage-html test-results
      env:
        XDEBUG_MODE: coverage

    - name: Upload code coverage report as an [artifact]
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results

  push_to_gh_pages:
    needs: run_tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout gh_pages branch from the repository
      uses: actions/checkout@v4
      with:
        ref: gh_pages

    - name: Set up Git and delete all files in the repository
      run: |
        git config user.name "roberto-manjarres-betancur"
        git config user.email "roberto.manjarres-betancur@moffitt.org"
        git rm -rf .

    - name: Download code coverage report [artifact] generated by the previous job
      uses: actions/download-artifact@v4
      with:
        name: test-results
        path: test-results

    - name: Remove underscore _ character from html files and folder names
      run: |
        find test-results -type f -name "*.html" -exec sed -i 's/_icons/.\/icons/g' {} +
        find test-results -type f -name "*.html" -exec sed -i 's/_css/.\/css/g' {} +
        find test-results -type f -name "*.html" -exec sed -i 's/_js/.\/js/g' {} +
        mv test-results/_css test-results/css
        mv test-results/_icons test-results/icons
        mv test-results/_js test-results/js
        mv test-results docs

    - name: Push the new test report the gh_pages branch
      run: |
        git add .
        git commit -m "Updated test results"
        git push
